name: ReportUI Version 1
author: Callum
website: https://github.com/techzonepro

version: 1.3.1
api: 3.0.2

main: Callum\ReportUI\ReportUI
depend: ["FormAPI"]

commands:
  report:
    description: Report a player
    permission: report.use
  reportadmin:
    description: Open Report Panel
    permission: report.admin

permissions:
  report.use:
    default: true
  report.admin:
    default: op
  report.admin.notification:
    default: op